### ISSUE TITLE
Solve the "topology problem"

### ISSUE THREAD

**Issue by simcard0000** [jazz-sim/crochet-craft#71]
**TO-DO:**

- As the title says. This could also be something we discuss with the graphics lab (see: https://github.com/jazz-sim/crochet-craft/issues/69).
- Allen (@AltheFlyer) has done the bulk of the thinking about it, but I've assigned a couple other people to this ticket such that we can help.
- Perhaps we set up a specific meeting where we just sort this out all together?

**Comment by simcard0000** [comment]
@AltheFlyer Should I close this since we now have a plan of sorts for rendering?

**Comment by AltheFlyer** [comment]
No
I'm not sure if the plan I had written out works beyond rectangle-based patterns

**Comment by simcard0000** [comment]
@AltheFlyer ok sounds good

**Comment by simcard0000** [comment]
Still open - however for further notes see [Design Decisions and Planning](https://docs.google.com/document/d/1fTPUgL46pOcHhEnXe7B1cuxIRZ2YGk3UH_CwM1BEsEY/edit?tab=t.0#heading=h.cd4nbjedi5k1).

**Comment by simcard0000** [comment]
Closing because it will come up in individual tickets.
