### ISSUE TITLE
Determine a grammar for the parser

### ISSUE THREAD

**Issue by simcard0000** [jazz-sim/crochet-craft#79]
**TO-DO**:
- Related to https://github.com/jazz-sim/crochet-craft/issues/66, just to make sure we have everything in the parser, define a formal grammar for the crochet input text.

**Comment by j-tai** [comment]
Added to design decisions doc
https://docs.google.com/document/d/1fTPUgL46pOcHhEnXe7B1cuxIRZ2YGk3UH_CwM1BEsEY/edit
